### ISSUE TITLE
Extend map to show json-area-results

### ISSUE THREAD

**Issue by tordans** [k-nut/pumpen-voronoi#3]
Hi @k-nut, I played around at https://github.com/tordans/pumpen-voronoi to extend the map with other data types.

However, for one of those requests I run in to a problem and I don't understand the code well enough to fix it: I extended the query to include way/osm-areas as well as nodes with a center-lat-lng-value. However, that value uses a different data structure (below). Where in the code are the black circles created? Which is probably where I need to add the if-else to change the lat/lon-values based on "node or way", right?

Nodes:
```
{
  "type": "node",
  "id": 352734260,
  "lat": 52.5398067,
  "lon": 13.5642190,
  "tags": {
  }
},
```

Ways/Areas
```
{
  "type": "way",
  "id": 4675776,
  "center": {
    "lat": 52.5330846,
    "lon": 13.3463428
  },
  "nodes": [ 29695389,… ],
  "tags": {
    "leisure": "playground"
  }
},
```

FYI, those maps are available once this works …
- https://tordans.github.io/pumpen-voronoi/#data=man_made--water_well
- https://tordans.github.io/pumpen-voronoi/#data=leisure--playground
- https://tordans.github.io/pumpen-voronoi/#data=playground--swing
- https://tordans.github.io/pumpen-voronoi/#data=bicycle_parking

**Comment by k-nut** [comment]
That sounds really good!

The part in the code where the points are added is here:
https://github.com/k-nut/pumpen-voronoi/blob/master/main.js#L79

At that point, `p` is an entry from the `data.json` file as highlighted here: https://github.com/k-nut/pumpen-voronoi/blob/master/data.json#L11-L28

For you this means that in that `filteredPoints.map` function you would probably want to check for the `type` of the current `p` and then return the type specific `latlng`.

**Comment by tordans** [comment]
Thanks. I managed to get a step closer with https://tordans.github.io/pumpen-voronoi/#data=leisure--playground. This issue is solved, I hope. 

But the maps are still buggy for some reason. Will look at it again later.
